name: release-tag

on:
  push

jobs:
  release-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_ORG: teacup
      DOCKER_LATEST: latest
      RUNNER_TOOL_CACHE: /toolcache
      MOAT_VERSION: v1.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(git describe --tags --always | sed 's/^v//') >> $GITHUB_OUTPUT                

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64                        
          push: true
          tags: | # replace it with your local IP and tags
            coltonh476/${{ steps.meta.outputs.REPO_NAME }}:${{ env.MOAT_VERSION }}
            coltonh476/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}
          build-args: MOAT_VERSION=${{ env.MOAT_VERSION }}